spring:
  application:
    name: 'coupon-panda'
  datasource:
    driver-class-name: org.h2.Driver
    url: jdbc:h2:~/test
    username: sa
    password:
  h2:                   # H2 Database
    console:
      enabled: true     # H2 Console 사용여부
      path: /h2-console # H2 Console 접속 Path
  sql:
    init:               # 더미 테이블, 데이터 생성
      mode: always
      schema-locations: classpath:/h2/schema.sql
      data-locations: classpath:/h2/data.sql
  jpa:
    hibernate:
      ddl-auto: create-drop      # 어플리케이션 시작 시 생성, 세션 종료 시 스키마 소멸
    properties:
      hibernate:
        show_sql: true   # Hibernate가 보내는 SQL 콘솔 출력
    defer-datasource-initialization: true   # Script 파일이 hibernate 초기화 후 동작
logging:
  level:
    org.h2: DEBUG
    org.springframework.jdbc.datasource.init.ScriptUtils: DEBUG
